

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin:"0px",padding:"0px"}}>{children}</body>
    </html>
  );
}
